# This notebook provides the commands needed to read in an NWB file with raw data taken from a trodes .rec file and to copy the relevant metadata into a DataJoint Schema designed to mimic NWB structure

## The following steps must be completed before running this notebook:
### 1) Set up access to a DataJoint database. See https://tutorials.datajoint.io/
### 2) Install pynwb. 
    See https://pynwb.readthedocs.io/en/stable/getting_started.html#installation
### 3) Install the ndx-fl-novela package. 
     conda install -c novelakrk ndx-fl-novela
### 4) Download the example franklab NWB file from DropBox. 
    https://www.dropbox.com/to_be_updated

#### Make sure we're in the franklabnwb/franklabnwb directory. 
#### Eventually this will be unnecessary because the package will properly installed

In [1]:
cd ../schema

/Users/loren/Src/NWB/nwb_datajoint/schema


#### Load all of the relevant modules

In [2]:

%load_ext autoreload
%autoreload 2


import pynwb
import os

#DataJoint and DataJoint schema
import datajoint as dj
dj.config["enable_python_native_blobs"] = True

import common_session
import common_ephys
import common_device
import common_lab
import common_task
import common_behav
import common_interval
import common_region
import common_filter
import nwb_dj

#franklabnwb functions
#from franklabnwb import fl_ns_path
#import franklabnwb.nspike_helpers as ns
#import franklabnwb.query_helpers as qu
#import franklabnwb.fl_extension as fle
#import franklabnwb.fl_extension as flh

Please enter DataJoint username:  root
Please enter DataJoint password:  ········


Connecting root@localhost:3306


11:40:21 [I] klustakwik KlustaKwik2 version 0.2.6


#### Next we specify the NWB file name and populate the rest of the schema
#### Replace the code below with the text for the path to the NWB file

In [3]:
nwb_raw_file_name = '/data/nwb_builder_test_data/beans20190718.nwb'

### temporary temporary file; FIX when NWB file handing sorted out

In [4]:
nwb_file_name = '/data/nwb_builder_test_data/beans20190718_pp.nwb'

In [8]:
nwb_dj.NWBPopulate([nwb_raw_file_name]) 

Importing NWB file /data/nwb_builder_test_data/beans20190718.nwb


/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/pynwb/file.py:404: DeprecationWarning: replaced by NWBFile.processing
  warn("replaced by NWBFile.processing", DeprecationWarning)
/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/pynwb/base.py:75: PendingDeprecationWarning: get_data_interface will be replaced by get
  warn(PendingDeprecationWarning('get_data_interface will be replaced by get'))


Importing raw data: Estimated sampling rate:	20000.0 Hz
                    Number of valid intervals:	5
Processing raw position data. Estimated sampling rate: 30.0 Hz


/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/pynwb/file.py:404: DeprecationWarning: replaced by NWBFile.processing
  warn("replaced by NWBFile.processing", DeprecationWarning)
/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/pynwb/base.py:75: PendingDeprecationWarning: get_data_interface will be replaced by get
  warn(PendingDeprecationWarning('get_data_interface will be replaced by get'))


#### The code below creates a diagram of the various schema and their relationships

In [11]:
common_ephys.ElectrodeSortingInfo().initialize(nwb_file_name)

[autoreload of common_ephys failed: Traceback (most recent call last):
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 302, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions

In [30]:
common_ephys.ElectrodeSortingInfo().set_reference_from_list(nwb_file_name, [[0, 10], [1, 11]])

[autoreload of common_ephys failed: Traceback (most recent call last):
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 302, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions

In [31]:
common_ephys.ElectrodeSortingInfo()

*nwb_file_name *electrode_id  sort_group     reference_elec
+------------+ +------------+ +------------+ +------------+
/data/nwb_buil 0              0              10            
/data/nwb_buil 1              0              11            
/data/nwb_buil 2              0              -1            
/data/nwb_buil 3              0              -1            
/data/nwb_buil 4              0              -1            
/data/nwb_buil 5              0              -1            
/data/nwb_buil 6              0              -1            
/data/nwb_buil 7              0              -1            
/data/nwb_buil 9              0              -1            
/data/nwb_buil 11             0              -1            
/data/nwb_buil 13             0              -1            
/data/nwb_buil 15             0              -1            
   ...
 (Total: 134)

In [22]:
elect = (common_ephys.ReferenceElectrode & {'nwb_file_name' : nwb_file_name}).fetch('electrode_id')
electtest = elect[:, np.newaxis]
electtest[0,1]

IndexError: index 1 is out of bounds for axis 1 with size 1

In [18]:
import numpy as np
with pynwb.NWBHDF5IO(a, "a") as io:
    nwbf= io.read()
nwbf
electrode_table_region = nwbf.create_electrode_table_region([0,2], 'filtered electrode table')
es = pynwb.ecephys.ElectricalSeries(name='filt test', data=np.empty((2,2), dtype='i2'),
                                    electrodes=electrode_table_region, timestamps= np.empty(0))
test = np.ones((10,1))
nwbf.add_scratch(test, "test data", notes="test")
#nwbf.add_analysis(es)
with pynwb.NWBHDF5IO(nwb_file_name, "a") as io:
    io.write(nwbf)

io.close()

/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py:436: BrokenLinkWarning: /acquisition/e-series
  warnings.warn(os.path.join(h5obj.name, k), BrokenLinkWarning)
/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py:436: BrokenLinkWarning: /general/devices/header_device
  warnings.warn(os.path.join(h5obj.name, k), BrokenLinkWarning)
/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py:436: BrokenLinkWarning: /general/devices/probe 0
  warnings.warn(os.path.join(h5obj.name, k), BrokenLinkWarning)
/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py:436: BrokenLinkWarning: /general/extracellular_ephys/0
  warnings.warn(os.path.join(h5obj.name, k), BrokenLinkWarning)
/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py:436: BrokenLinkWarning: /general/extracellular_ephys/1
  wa

Exception: Could not construct DynamicTable object due to: 'x'

In [17]:
common_ephys.Raw()

*nwb_file_name interval_name  nwb_object_id  sampling_rate  comments       description   
+------------+ +------------+ +------------+ +------------+ +------------+ +------------+
/data/nwb_buil raw data valid 492a9259-228c- 20000.0        sample comment Electrical ser
 (Total: 1)

In [22]:
common_session.LinkedNwbfile().delete()

About to delete:
`common_session`.`linked_nwbfile`: 1 items


Proceed? [yes, No]:  yes


Committed.


In [39]:
common_filter.create_standard_filters()
common_ephys.LFPElectrode().set_lfp_elect([1])
common_ephys.LFP().populate()

[[1.56348899e+09 1.56348909e+09]]
Output array should have shape (100000, 1) and dtype <f8
Checking output array shape is disabled, make sure portion of output array has shape (100000, 1)
past append
writing new NWB file /data/nwb_builder_test_data/beans20190718_pp00000000.nwb
filtered data pynwb.ecephys.ElectricalSeries at 0x4861722960
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "filtered_data": shape (100000, 1), type "<i2">
  description: no description
  electrodes: electrodes <class 'hdmf.common.table.DynamicTableRegion'>
  interval: 1
  resolution: -1.0
  timestamps: <HDF5 dataset "timestamps": shape (100000,), type "<f8">
  timestamps_unit: seconds
  unit: volts

{'nwb_file_name': '/data/nwb_builder_test_data/beans20190718_pp.nwb', 'interval_name': 'raw data valid times', 'sampling_rate': 20000, 'filter_name': 'LFP 0-400 Hz', 'filter_sampling_rate': 20000, 'linked_file_name': '/data/nwb_builder_test_data/beans20190718_pp00000000.nwb', 'nwb_object_id':

In [51]:
common_ephys.LFP().delete()

About to delete:
`common_ephys`.`__l_f_p`: 1 items


Proceed? [yes, No]:  yes


Committed.


In [41]:
common_session.LinkedNwbfile()

*nwb_file_name *linked_file_n
+------------+ +------------+
/data/nwb_buil /data/nwb_buil
 (Total: 1)

In [7]:
common_session.Nwbfile().delete()

About to delete:
`common_ephys`.`electrode_config__electrode`: 134 items
`common_ephys`.`electrode_config__electrode_group`: 2 items
`common_ephys`.`electrode_config`: 1 items
`common_ephys`.`raw`: 1 items
`common_interval`.`interval_list`: 5 items
`common_session`.`_experimenter_list__experimenter`: 1 items
`common_session`.`_experimenter_list`: 1 items
`common_session`.`_session`: 1 items
`common_session`.`nwbfile`: 1 items


Proceed? [yes, No]:  yes


Committed.


In [ ]:
common_session.LinkedNwbfile()

In [20]:
interval_list = (common_interval.IntervalList() & {'nwb_file_name': nwb_file_name ,
                                                           'interval_name': 'raw data valid times'}).fetch1('valid_times')

[autoreload of common_ephys failed: Traceback (most recent call last):
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 302, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions

In [6]:
#### And now that we have the data in DataJoint, we can do queries to find time intervals we might be interested in
#### In the example below, we get all of the intervals where the task_name was sleep.

In [7]:
common_device.Probe.drop()

`common_device`.`probe` (0 tuples)
`common_device`.`probe__shank` (0 tuples)
`common_device`.`probe__electrode` (0 tuples)
`common_ephys`.`_electrode_config__electrode_group` (0 tuples)
`common_ephys`.`_units` (0 tuples)
`common_ephys`.`_electrode_config__electrode` (0 tuples)
`common_ephys`.`l_f_p_electrode` (0 tuples)
`common_ephys`.`__l_f_p` (0 tuples)
`common_ephys`.`l_f_p_band_parameters` (0 tuples)
`common_ephys`.`__l_f_p_band` (0 tuples)
`common_ephys`.`__decomp_series` (0 tuples)


Proceed? [yes, No]:  yes


Tables dropped.  Restart kernel.


In [26]:
sleep_intervals['valid_times']

array([array([1.13614661e+09, 1.13614794e+09]),
       array([1.13614908e+09, 1.13615003e+09]),
       array([1.13615118e+09, 1.13615241e+09]),
       array([1.13615411e+09, 1.13615495e+09])], dtype=object)

In [3]:
common_ephys

NameError: name 'common_ephys' is not defined

In [3]:
common_session.Nwbfile.drop()

`common_session`.`nwbfile` (0 tuples)
`common_session`.`_session` (0 tuples)
`common_session`.`_session__data_acq_device` (0 tuples)
`common_session`.`_experimenter_list` (0 tuples)
`common_session`.`_experimenter_list__experimenter` (0 tuples)
`common_interval`.`interval_list` (0 tuples)
`common_ephys`.`_electrode_config` (0 tuples)
`common_ephys`.`_electrode_config__electrode_group` (0 tuples)
`common_session`.`linked_nwbfile` (0 tuples)


Proceed? [yes, No]:  yes


Tables dropped.  Restart kernel.


In [21]:
common_device.Probe().Electrode()

*probe_type    *probe_shank   *probe_electro contact_size   rel_x     rel_y      rel_z    
+------------+ +------------+ +------------+ +------------+ +-------+ +--------+ +-------+
128c-4s8mm6cm- 0              0              20.0           0.0       0.0        0.0      
128c-4s8mm6cm- 0              1              20.0           0.0       -40.0      0.0      
128c-4s8mm6cm- 0              2              20.0           0.0       -80.0      0.0      
128c-4s8mm6cm- 0              3              20.0           0.0       -120.0     0.0      
128c-4s8mm6cm- 0              4              20.0           0.0       -160.0     0.0      
128c-4s8mm6cm- 0              5              20.0           0.0       -200.0     0.0      
128c-4s8mm6cm- 0              6              20.0           0.0       -240.0     0.0      
128c-4s8mm6cm- 0              7              20.0           0.0       -280.0     0.0      
128c-4s8mm6cm- 0              8              20.0           0.0       -320.0     0.0      
128c-4s8mm6cm- 0              9              20.0           0.0       -360.0     0.0      
128c-4s8mm6cm- 0              10             20.0           0.0       -400.0     0.0      
128c-4s8mm6cm- 0              11             20.0           0.0       -440.0     0.0      
   ...
 (Total: 128)

In [10]:
common_ephys

In [5]:
a = common_ephys.SpikeSortingGroup().set_by_electrode_group(nwb_file_name)

In [9]:
p = (common_ephys.SpikeSorterParameters() & {'sorter_name': 'mountainsort4'}).fetch()

In [10]:
p

array([('mountainsort4', 'default', {'detect_sign': -1, 'adjacency_radius': -1, 'freq_min': 300, 'freq_max': 6000, 'filter': True, 'whiten': True, 'curation': False, 'num_workers': None, 'clip_size': 50, 'detect_threshold': 3, 'detect_interval': 10, 'noise_overlap_threshold': 0.15})],
      dtype=[('sorter_name', 'O'), ('parameter_set_name', 'O'), ('parameter_dict', 'O')])

In [25]:
import os
import pynwb
import ndx_fl_novela.probe
import numpy as np

nwb_file_name = '/data/nwb_builder_test_data/beans20190718s1.nwb'

in_io  = pynwb.NWBHDF5IO(nwb_file_name, 'r')
nwbf_in = in_io.read()

nwbf_out = nwbf_in.copy()


n_linked_files = 4
# name the file, adding the number of links with preceeding zeros
nwb_out_file_name = os.path.splitext(nwb_file_name)[0] + str(n_linked_files).zfill(5) + '.nwb'

# write the linked file
print(f'writing new NWB file {nwb_out_file_name}')
with pynwb.NWBHDF5IO(nwb_out_file_name, mode='a', manager=in_io.manager) as io:
    electrode_table_region = nwbf_out.create_electrode_table_region([0],
                                                                        'filtered electrode table')
    filtered_data = np.array([3, 4, 5])
    timestamps = np.array([1, 2, 3])

    # FIX: name needs to be unique
    es = pynwb.ecephys.ElectricalSeries('filtered data', filtered_data, electrode_table_region,
                                        timestamps=timestamps)
    nwbf_out.add_acquisition(es)
    print(nwbf_out.get_acquisition('filtered data'))
    io.write(nwbf_out)
    


in_io.close()

# test append to file - this works
#new_io = pynwb.NWBHDF5IO(nwb_out_file_name, 'r')
#nwbf_new = new_io.read()
#a = nwbf_new.get_
#new_io.close()

writing new NWB file /data/nwb_builder_test_data/beans20190718s100004.nwb
filtered data pynwb.ecephys.ElectricalSeries at 0x4878606992
Fields:
  comments: no comments
  conversion: 1.0
  data: [3 4 5]
  description: no description
  electrodes: electrodes <class 'hdmf.common.table.DynamicTableRegion'>
  interval: 1
  resolution: -1.0
  timestamps: [1 2 3]
  timestamps_unit: seconds
  unit: volts



/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/hdmf/build/objectmapper.py:225: DtypeConversionWarning: Spec 'ElectricalSeries/timestamps': Value with data type int64 is being converted to data type float64 as specified.
  warnings.warn(full_warning_msg, DtypeConversionWarning)


In [11]:
electrodes = (common_ephys.ElectrodeConfig.Electrode() & {'nwb_file_name' : nwb_file_name} & {'bad_channel' : 'False'}).fetch()

[autoreload of common_ephys failed: Traceback (most recent call last):
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 302, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions

In [14]:
elect_info = (electrodes['electrode_group_name'], electrodes['probe_shank'])

[autoreload of common_ephys failed: Traceback (most recent call last):
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 302, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions

In [17]:
import numpy as np
egroups = np.unique(electrodes['electrode_group_name'])


In [18]:
egroups

array(['0', '1'], dtype=object)

In [20]:
e = egroups[0]

In [25]:
shanks = electrodes['probe_shank'][electrodes['electrode_group_name'] == e]

In [31]:
shank_dict = dict()
# for each electrode group, get a list of the unique shanks
shank_dict[e] = np.unique(electrodes['probe_shank'][electrodes['electrode_group_name'] == e])

In [32]:
dj.Diagram

array([0, 1, 2, 3])

In [50]:
sort_group = 0
elect_dict = dict()
elect_dict['nwb_file_name'] = nwb_file_name
for e_group in egroups:
    elect_dict['electrode_group_name'] = e_group
    # for each electrode group, get a list of the unique shank numbers
    shank_list = np.unique(electrodes['probe_shank'][electrodes['electrode_group_name'] == e_group])
    # get the indices of all electrodes in for this group / shank and set their sorting group
    for shank in shank_list:
        shank_elect = electrodes['electrode_id'][np.logical_and(electrodes['electrode_group_name'] == e_group,
                                                                electrodes['probe_shank'] == shank)]
    # create a 2d array for these electrodes
    sort_insert = list()
    for elect in shank_elect:
        sort_insert.append([nwb_file_name, e_group, elect, sort_group])

[autoreload of common_ephys failed: Traceback (most recent call last):
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 410, in superreload
    update_generic(old_obj, new_obj)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 302, in update_class
    if update_generic(old_obj, new_obj): continue
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 347, in update_generic
    update(a, b)
  File "/Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/IPython/extensions

In [51]:
sort_insert

[['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 225, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 227, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 229, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 231, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 233, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 235, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 237, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 239, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 241, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 243, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 245, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 247, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 249, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.nwb', '1', 251, 0],
 ['/data/nwb_builder_test_data/beans20190718_pp.

In [47]:
a

[1, '/data/nwb_builder_test_data/beans20190718_pp.nwb']